version: "3"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: bellchan-bot
    container_name: bellchan-bot
    depends_on:
      - redis
    environment:
      - RUN_CONTEXT=
      - SLACK_API_TOKEN
      - DEFAULT_CHANNEL_ID
      - BOT_ID
      - BOT_NAME
      - BOT_ICON_URL
      - REDIS_URL=redis://h:@redis:6379
      - HEROKU_API_KEY
    networks:
      app:
    volumes:
      - .:/opt/bellchan
  redis:
    image: redis:7.0
    container_name: bellchan-redis
    networks:
      app:
    ports:
      - 6380:6379

networks:
  app:
