FROM python:3.10.3 as builder

WORKDIR /opt

ADD https://github.com/cortesi/modd/releases/download/v0.8/modd-0.8-linux64.tgz .
RUN tar xvf modd-0.8-linux64.tgz


FROM python:3.10.3

ENV TZ Asia/Tokyo

WORKDIR /opt/bellchan

COPY --from=builder /opt/modd-0.8-linux64/modd /usr/local/bin/

COPY ./requirements-dev.txt .
COPY ./requirements.txt .

RUN pip install -U pip \
    && pip install --no-cache-dir -r requirements-dev.txt

COPY ./run.py .
COPY ./bellchan bellchan

CMD ["modd"]
