working_directory: &working_directory ~/bellchan

images:
  python: &python_image circleci/python:3.9.1

pip:
  restore_cache: &pip_restore_cache
    keys:
      - pip-v4-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
      - pip-v4-{{ .Branch }}-
      - pip-v4-

  install:  &pip_install
    name: Install pip packages
    command: pip install -r requirements-dev.txt

  save_cache: &pip_save_cache
    key: pip-v4-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
    paths:
      - .venv

version: 2
jobs:
  flake8:
    working_directory: *working_directory
    docker:
      - image: *python_image
    steps:
      - checkout
      - restore_cache:
          <<: *pip_restore_cache
      - run:
          <<: *pip_install
      - save_cache:
          <<: *pip_save_cache
      - run:
          name: Run flake8
          command: make lint/flake8

workflows:
  version: 2
  test:
    jobs:
      - flake8
