version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  flake8:
    executor:
      name: python/default
      tag: 3.9.1
    environment:
      RUN_CONTEXT: ""
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements-dev.txt
          pkg-manager: pip
          cache-version: v1
      - run:
          name: Run flake8
          command: make lint/flake8

workflows:
  version: 2
  test:
    jobs:
      - flake8
