working_directory: &working_directory ~/bellchan

images:
  python: &python_image circleci/python:3.9.1

pip:
  restore_cache: &pip_restore_cache
    keys:
      - pip-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - pip-v1-{{ .Branch }}-
      - pip-v1-

  install:  &pip_install
    name: Install pip packages
    command: |
      pip install pipenv
      pipenv install --dev

  save_cache: &pip_save_cache
    key: pip-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
    paths:
      - .venv

version: 2
jobs:
  flake8:
    working_directory: *working_directory
    docker:
      - image: *python_image
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          <<: *pip_restore_cache
      - run:
          <<: *pip_install
      - save_cache:
          <<: *pip_save_cache
      - run:
          name: Run flake8
          command: |
            pipenv run lint

workflows:
  version: 2
  test:
    jobs:
      - flake8
